django_site_labs/blog/urls.py
from django.urls import path
from . import views

app_name = "blog" # Namespace for the name field of the path, eg. {% url 'blog:posts_list' %}

urlpatterns = [
    # path("", views.index, name="index"),
    path("", views.IndexView.as_view(), name="index"),
    # path("posts", views.posts_list, name="posts_list"),
    path("posts", views.PostsListView.as_view(), name="posts_list"),
    # path("posts/<slug:slug>", views.post_detail, name="post_detail"), # /post/first-post
    path("posts/<slug:slug>", views.PostDetailView.as_view(), name="post_detail"), # /post/first-post
    path("read-later", views.ReadLaterView.as_view(), name="read_later")
]

django_site_labs/blog/templates/blog/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Teddy's Dev Blog
{% endblock %}

{% block css_files %}
    <link rel="stylesheet" href="{% static 'blog/css/post.css' %}" />
    <link rel="stylesheet" href="{% static 'blog/css/index.css' %}" />
{% endblock %}

{% block content %}
    <section id="welcome">
        <header>
            <img src="{% static 'blog/images/self.png' %}" alt="Dev Blog Logo" />
            <h2>Teddy's Dev Blog</h2>
        </header>
        <p>Hi! I'm Teddy, a software developer passionate about coding and technology.</p>
        <p>I love sharing my knowledge, insights, and experiences from my journey in software development.</p>
    </section>
    
    <section id="latest-posts">
        <h2>My Latest Thoughts</h2>
        
        <ul>
            {% for post in posts %}
                {% include "blog/includes/post.html" %}
            {% endfor %}
        </ul>
    </section>

    <section id="about">
        <h2>What I Do</h2>
        <p>
            I love programming, exploring new technologies, and sharing my knowledge with others through this blog.
        </p>
        <p>
            My goal is to inspire and help fellow developers on their coding journeys.
        </p>
    </section>


{% endblock %}

django_site_labs/blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block css_files %}
    <link rel="stylesheet" href="{% static 'blog/css/post_detail.css' %}" />
{% endblock %}

{% block content %}
    {% if comment_form.errors %}
        <div id="alert">
            <h2>Saving the comment failed!</h2>
            <p>Please check the comment form below the post and fix your erros.</p>
            <a href="#comment-form">Fix!</a>
        </div>
    {% endif %}
    <section id="summary">
        <h2> {{post.title}} </h2>
        <div>
            {% for tag in post_tags%}
                <span class="tag">{{ tag.caption }}</span>
            {% endfor %}
        </div>
        <div id="read-later">
            <form action="{% url "blog:read_later" %}" method="POST">
                {% csrf_token %}
                <input type="hidden" value="{{ post.id }}" name="post_id">
                <button>
                    {% if saved_for_later %}
                        Remove from "Read Later" List
                    {% else %}
                        Read Later
                    {% endif %}
                </button>
            </form>
        </div>
        <article>
            {% comment %} <img src="{% static "blog/images/"|add:post.image %}" alt="{{post.title}}"/> {% endcomment %}
            {% comment %} <img src="{% static "blog/images/"|add:post.image_name %}" alt="{{post.title}}"/> {% endcomment %}
            <img src="{{ post.image.url }}" alt="{{post.title}}"/>
            <address>By <a href="mailto:{{ post.author.email_address }}">{{ post.author }}</a></adress>
            <div>
                Last updated on <time>{{ post.date|date:"d M Y" }}</time>
            </div>
        </article>
    </section>
    <main>
        <p>
            {% comment %} linebreaks filter preserve linebreaks {% endcomment %}
            {{ post.content|linebreaks }}
        </p>
    </main>

    <section id="comments">
        <ul>
            {% for comment in comments %}
            <li>
                <h2>{{ comment.user_name }}</h2>
                <p>{{ comment.text|linebreaks }}</p>
            </li>
            {% endfor %}
        </ul>
    </section>

    <section id="comment-form">
        <h2>Your Comment</h2>
        {% comment %} be careful with the namespace of the url name {% endcomment %}
        <form action="{% url "blog:post_detail" post.slug %}" method="POST">
            {% csrf_token %}
            {% for form_field in comment_form %}
            <div class="form-control {% if form_field.errors %}invalid{% endif %}">
                {{ form_field.label_tag }}
                {{ form_field }}
                {{ form_field.errors }}
            </div>
            {% endfor %}
            <button>Save Comment</button>
        </form>
    </section>
{% endblock %}

django_site_labs/blog/templates/blog/posts_list.html
{% extends "base.html" %}
{% load static %}

{% comment "" %} This is modified from the all-post.html file {% endcomment %}

{% block title %}
    All Posts - Teddy's Dev Blog
{% endblock %}

{% block css_files %}
    <link rel="stylesheet" href="{% static 'blog/css/post.css' %}" />
    <link rel="stylesheet" href="{% static 'blog/css/posts_list.css' %}" />
{% endblock %}

{% block content %}
    <section id="all-posts">
        <h2>My Collected Posts</h2>
        <ul>
            {% for post in posts %}
                {% include "blog/includes/post.html" %}
            {% endfor %}
        </ul>

    </section>
{% endblock %}

django_site_labs/blog/templates/blog/stored_posts.html
{% extends "base.html" %}
{% load static %}

{% block title %} 
My Stored Posts
{% endblock %} 

{% block css_files %}
<link rel="stylesheet" href="{% static "blog/css/stored_posts.css" %}">
{% endblock %}

{% block content %}
  <section id="stored-posts">
    {% if not has_posts %}
      <p>You didn't save any posts for later.</p>
    {% endif %}
    <ul>
      {% for post in posts %}
        <li><a href="{% url "blog:post_detail" post.slug %}">{{ post.title }}</a></li>
      {% endfor %}
    </ul>
  </section>
{% endblock %}