django_site_labs/blog/urls.py
from django.urls import path
from . import views

app_name = "blog" # Namespace for the name field of the path, eg. {% url 'blog:posts_list' %}

urlpatterns = [
    # path("", views.index, name="index"),
    path("", views.IndexView.as_view(), name="index"),
    # path("posts", views.posts_list, name="posts_list"),
    path("posts", views.PostsListView.as_view(), name="posts_list"),
    # path("posts/<slug:slug>", views.post_detail, name="post_detail"), # /post/first-post
    path("posts/<slug:slug>", views.PostDetailView.as_view(), name="post_detail"), # /post/first-post
    path("read-later", views.ReadLaterView.as_view(), name="read_later")
]

django_site_labs/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # path("admin/", admin.site.urls),
    path("top-secret-admin666/", admin.site.urls),
    # path("blog/", include("blog.urls")), # ie. include app/urls.py, and link https://localhost:8000/blog/ to it
    path("", include("blog.urls")),        # Here, we set the blog app to be the root of the site, ie. link https://localhost:8000/ to it
] # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_site_labs/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Django Site{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
    {% block css_files %}
    {% endblock %}
</head>
<body>
    <header id="main-navigation">
        <h1><a href="{% url 'blog:index'%}">Teddy's Dev Blog</a></h1>
        <nav>
            <a href="{% url "blog:read_later" %}">Stored Posts</a>
            <a href="{% url "blog:posts_list" %}">All Posts</a>
        </nav>
    </header>
    {% block content %}
    {% endblock %}
</body>
</html>